server:
  port: 8080
  servlet:
    context-path: /client2
 
client2.message: "I am client2"
demo.message: "Test Client Invoke 4 - Test Strategy"
management.endpoints.web.exposure.include: "*"
